### PR TITLE
Fix create instance func

### LINKED ISSUE #1425: When register a Abstract Class using GDREGISTER_CLASS(), compiled without error
### Godot version

4.3.dev(29b3d9e)

### godot-cpp version

4.3.dev(a62f633)

### System information

windows 11

### Issue description

Created an **Abstract class** that inherits from Node. When I registered this class **using GDREGISTER_CLASS()** in register_types.cpp and compiled the project, the C++ did not report any errors. 

Open the engine, and selecte this class to create a root node, it will print error:
QQ截图20240329171501

The expected result is that when I register an abstract class with GDREGISTER_CLASS(), the project cannot be compiled. 

I analyzed and it seems that the following code caused the class constructor to be skipped during compilation:
```
// class_db.hpp
template <class T>
static GDExtensionObjectPtr _create_instance_func(void *data) {
	if constexpr (!std::is_abstract_v<T>) {
		T *new_object = memnew(T);
		return new_object->_owner;
	} else {
		return nullptr; // <- will execute this line
	}
}
```

### Steps to reproduce

- create an abstract class like:

```
class Foo : public Node {
  GDCLASS(Foo, Node)

  virtual void func() = 0;
};
```

- register class in register_types.cpp:
```
GDREGISTER_CLASS(Foo);
```

- compile the project, will successed.

- open the engine and create this class with error

### Minimal reproduction project

N/A

### PR DESCRIPTION
**Pull request by pupil1337**
To Fix #1425

This PR is a resubmission of #1427 , as the repository submitted that time was my master branch it looked bad. So I want to resubmit it.

### CODE REVIEW

**Comment by dsnopek** [comment]
Thanks!

The goal here sounds great: cause a compilation error if trying to register an abstract class with `GDREGISTER_CLASS()` (rather than `GDREGISTER_ABSTRACT_CLASS()`).

However, I think the implementation here will be confusing for developers (the error they get when using the wrong macros doesn't point to the solution) and for maintainers (my brain has trouble with the `!std::is_abstract_v<T> || !is_abstract` condition :-)).

What if we added another `static_assert()` to the top of `ClassDB::_register_class()` instead?

Something like:

```
	static_assert(std::is_abstract_V<T> && !is_abstract, "Abstract classes must be registered using GDREGISTER_ABSTRACT_CLASS().");
```

**Comment by pupil1337** [comment]
> Thanks!
> 
> The goal here sounds great: cause a compilation error if trying to register an abstract class with `GDREGISTER_CLASS()` (rather than `GDREGISTER_ABSTRACT_CLASS()`).
> 
> However, I think the implementation here will be confusing for developers (the error they get when using the wrong macros doesn't point to the solution) and for maintainers (my brain has trouble with the `!std::is_abstract_v<T> || !is_abstract` condition :-)).
> 
> What if we added another `static_assert()` to the top of `ClassDB::_register_class()` instead?
> 
> Something like:
> 
> ```
> 	static_assert(std::is_abstract_V<T> && !is_abstract, "Abstract classes must be registered using GDREGISTER_ABSTRACT_CLASS().");
> ```

Thank you for your suggestion, it's very useful! I had change last commit.

**Comment by dsnopek** [comment]
Thanks!

Two additional notes:

- I think this should be in `ClassDB::_register_class()` (with a leading underscore) rather than `ClassDB::register_class()`, because otherwise we have this same problem with `GDREGISTER_RUNTIME_CLASS()` or `GDREGISTER_INTERNAL_CLASS()`.
- In the error message, we should only recommend the macro (`GDREGISTER_CLASS()`) not the function. Despite using the functions directly in the test code (which will be fixed soon by PR https://github.com/godotengine/godot-cpp/pull/1435) we want to encourage developers to use the macros.

File: include/godot_cpp/core/class_db.hpp [hunk 1]
```diff
@@ -203,6 +203,7 @@ class ClassDB {
 template <typename T, bool is_abstract>
 void ClassDB::_register_class(bool p_virtual, bool p_exposed, bool p_runtime) {
 	static_assert(TypesAreSame<typename T::self_type, T>::value, "Class not declared properly, please use GDCLASS.");
+	static_assert(!std::is_abstract_v<T> || is_abstract, "Class is abstract, please use GDREGISTER_ABSTRACT_CLASS.");
```
Comment (pupil1337) [inline include/godot_cpp/core/class_db.hpp:206]: - if this class is real a no-abstract class, not check, so it can register by `GDREGISTER_CLASS` `GDREGISTER_VIRTUAL_CLASS` `GDREGISTER_ABSTRACT_CLASS` `GDREGISTER_INTERNAL_CLASS` `GDREGISTER_RUNTIME_CLASS` etc.. (all register methods)
- and if this class is real an abstract class, check `is_abstract` param, make this class must register by `GDREGISTER_ABSTRACT_CLASS`

**Review by dsnopek — APPROVED** [review]
Thanks, this looks great to me now!

**Comment by dsnopek** [comment]
Congrats on your first merged Godot contribution :tada:

**Comment by pupil1337** [comment]
Thanks🌹

**Comment by dsnopek** [comment]
Cherry-picked for 4.2 in PR https://github.com/godotengine/godot-cpp/pull/1465

**Comment by dsnopek** [comment]
Cherry-picked for 4.1 in PR https://github.com/godotengine/godot-cpp/pull/1466
